Added the option to use TestMode for /UI5/ABAP_REPOSITORY_SRV
pfefferf/ui5-nwabap-deployer pull request #51
Opened 2021-07-19 09:46 UTC by Fjaoos

Hi,

I wanted to be able to use the TestMode of the OData Service /UI5/ABAP_REPOSITORY_SRV , which is used since version 2 of this project.

You can set the environment variable UI5_TASK_NWABAP_DEPLOYER__TESTMODE to true if you want to use the TestMode.

I added this functionality to test the yaml config against the real system before I try to deploy the code

2021-07-19 13:35 UTC, pfefferf commented on packages/ui5-nwabap-deployer-core/lib/UI5ABAPRepoClient.js
> +            sUrl + "$TestMode=TRUE";
What means the $ here? Should be a &.

2021-07-19 13:36 UTC, pfefferf requested changes
Issues to be fixed.

2021-07-19 13:38 UTC, Fjaoos commented on packages/ui5-nwabap-deployer-core/lib/UI5ABAPRepoClient.js
> +            sUrl + "$TestMode=TRUE";
I am so sorry, that was a typo.

2021-07-20 06:21 UTC, pfefferf commented
Thx for the contribution; I will integrate it probably next weekend (incl. enhancement of cli + grunt tooling with the same option)

2021-07-20 06:24 UTC, pfefferf approved these changes

2021-07-20 06:46 UTC, Fjaoos commented
Hi,
you are welcome. I am waiting for this function to be used by our Jenkins server so I would appreciate it very much if you could integrate this now and maybe add the grunt/cli tooling later on? I would have done it myself but I do not have the necessary testing configurations.

2021-07-20 06:49 UTC, pfefferf commented
I don't have access to my test environment too until end of the wekk. So I cannot do it now. Sorry.

2021-07-21 05:50 UTC, merged

2021-07-21 09:24 UTC, pfefferf commented
Found some time (and a another test environment) to enhance the coding:  Test Mode is available for the grunt, ui5 task, cli tooling.
Added some additional logic to avoid transport creation in case of a test deployment to avoid the situation that unused transports will be created each time a test deployment is done.

Checked if test mode is supported for undeployment too ... but unfortunately not.

2021-07-21 09:27 UTC, Fjaoos commented
That is interesting and I did not check for created transports. In my opinion the service should not create a transport in testMode. I will test that and might open an incident at SAP because this seems wrong for me.

2021-07-21 09:29 UTC, pfefferf commented
This is only related to the "transport handling" stuff within that package (not an issue of the service).

2021-07-21 14:08 UTC, Fjaoos commented
I tested the testMode a little bit more and found a problem with the error handling. A successfull test respods with status 403 and message class /UI5/UI5_REP_LOAD/004 which indicates no found error. 
![image](https://user-images.githubusercontent.com/19299859/126502608-c0374e0f-c709-42bc-b9cf-f0abcd478fe2.png)
I will investigate and provice a PR with a fix

2021-07-21 14:26 UTC, pfefferf commented
And what is the issue in the deployer? It does not react on 403.

2021-07-21 14:32 UTC, Fjaoos commented
The deployer does throw an error if the status code is 403. Since this is the wanted by the Service
![image](https://user-images.githubusercontent.com/19299859/126506348-bb15e671-aa15-4922-83ed-b32f73fb593a.png)
I think it would be to check the response body for /UI5/UI5_REP_LOAD/004 if the testMode is used.